# Generated by Django 2.1 on 2018-08-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_name', models.CharField(max_length=100, verbose_name="Student's Name")),
                ('mail', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('fathers_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mothers_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('guardian_phone_number', models.CharField(max_length=13, verbose_name="Guardian's Phone Number")),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='display_picture',
            field=models.ImageField(upload_to='api/pictures'),
        ),
    ]
